Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
]



#Add URL maps to redirect the base URL to our application

urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/resultados/', views.resultados, name='resultados'),
    path('<int:post_id>/likes/', views.likes, name='likes'),
]

blog/models.py
from django.db import models
import datetime
from django.utils import timezone


# Create your models here.


class Post(models.Model):
    post_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.post_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)      

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=200)
    likes = models.IntegerField(default=0)
    def __str__(self):
        return self.comment_text

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse
from django.template import loader
 
from .models import Post

# Create your views here.
def index(request):
    latest_post_list = Post.objects.order_by('-pub_date')[:5]
    context = {'latest_post_list': latest_post_list}
    return render(request, 'blog/index.html', context)

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/detail.html', {'post': post})

def resultados(request, post_id):
    response = "Estas viendo el post # %s."
    return HttpResponse(response % post_id)

def likes(request, post_id):
    return HttpResponse("Te gusta %s." % post_id)

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog!</title>
</head>
<body>
    <h1>{{ post.pub_date }}</h1>
    <h1>{{ post.post_text }}</h1>
    <ul>
    {% for comment in post.comment_set.all %}
        <li>{{ comment.comment_text }}</li>
    {% endfor %}
    </ul> 
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Pagina de Blog</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    {% if latest_post_list %}
    <ul>
    {% for post in latest_post_list %}
        <li><a href="{% url 'blog:detail' post.id %}">{{ post.post_text }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No Blogs por el momento.</p>
    {% endif %}    

    
</body>
</html>